### ISSUE TITLE
Please add Remember password

### ISSUE THREAD

**Issue by SymoHTL** [tevkr/Steam-Connection#1]
Please add this fuctionality. It is very "confusing" when u must alwasy put in steam guard code
THX

**Comment by tevkr** [comment]
Added. Thanks for the issue.

**Comment by tevkr** [comment]
Found a bug when using "Remember password" and "Close the program afer loggin in to your account" together.

**Comment by tevkr** [comment]
Fixed, [release link](https://github.com/tevkr/Steam-Connection/releases/tag/V1.0.1.1).
Thanks for the issue.
